// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9ZFlMRF2jRFZ5HK7ctVt7Y6bGuJKM3FU',
    appId: '1:175915705561:web:ef1c01298bf7e2e2c64ac8',
    messagingSenderId: '175915705561',
    projectId: 'food-delivery-799d8',
    authDomain: 'food-delivery-799d8.firebaseapp.com',
    storageBucket: 'food-delivery-799d8.appspot.com',
    measurementId: 'G-5P4M6PTE17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe1vKbOhS3Sp2Vu2dF9DOQT5ep2sUntBk',
    appId: '1:175915705561:android:d526ddf3ffa206b4c64ac8',
    messagingSenderId: '175915705561',
    projectId: 'food-delivery-799d8',
    storageBucket: 'food-delivery-799d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWRhPtTY2CrfY80Td_9jlkp1VLOcqA5CU',
    appId: '1:175915705561:ios:eadae559fa7516b7c64ac8',
    messagingSenderId: '175915705561',
    projectId: 'food-delivery-799d8',
    storageBucket: 'food-delivery-799d8.appspot.com',
    iosBundleId: 'com.example.fooddeliveryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWRhPtTY2CrfY80Td_9jlkp1VLOcqA5CU',
    appId: '1:175915705561:ios:eadae559fa7516b7c64ac8',
    messagingSenderId: '175915705561',
    projectId: 'food-delivery-799d8',
    storageBucket: 'food-delivery-799d8.appspot.com',
    iosBundleId: 'com.example.fooddeliveryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9ZFlMRF2jRFZ5HK7ctVt7Y6bGuJKM3FU',
    appId: '1:175915705561:web:0a18399e6f948a54c64ac8',
    messagingSenderId: '175915705561',
    projectId: 'food-delivery-799d8',
    authDomain: 'food-delivery-799d8.firebaseapp.com',
    storageBucket: 'food-delivery-799d8.appspot.com',
    measurementId: 'G-H5D66C6CVH',
  );
}
